#define HOURS	"Hours:"
#define MINUTES	"Minutes:"
#define SECONDS	"Seconds:"
#define	CM_STRING "Choose mode:" 
#define	CM_QUIT_STRING "Quit config mode." 
#define	CM_ALARM_STRING "Set alarm?" 
#define	SM_ALARM_STRING "Set alarm:" 
#define	CM_CLOCK_STRING "Set clock?" 
#define	SM_CLOCK_STRING "Set clock:" 